name: Yuna Sales Auto Tracker

on:
  schedule:
    - cron: '*/10 * * * *' # 每 10 分鐘執行一次
  workflow_dispatch: # 允許手動點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Tracker
        run: python track.py
